name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: apt install
      run: sudo apt-get install qt5-default cmake qtbase5-dev libmagick++-dev liblcms2-dev
    - name: build/test/install
      run: |
        sudo mkdir -p /opt/deploy/tests
        sudo chmod 777 /opt/deploy
        mkdir build && cd build
        cmake ..
        make
        make test || cp Testing/Temporary/LastTest.log /opt/deploy/tests/ && cp *.tif *.jpg /opt/deploy/tests/ && exit 1
        sudo make install
    - name: upload artifacts
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: tests-artifacts
        path: /opt/deploy/tests/