name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt update
      run: sudo apt-get update
    - name: apt install
      run: sudo apt-get install qt5-default cmake qtbase5-dev libmagick++-dev liblcms2-dev
    - name: build/test/install
      run: |
        mkdir build && cd build
        cmake ..
        make
        make --output-on-failure test
        sudo make install

